name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Up Python for ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
  
      - name: Installing Dependencies
        run: pip install tox tox-gh-actions
        
      - name: Running tests with Tox
        run: tox

  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask_starter:$(date +%s)
